spring.application.name=mvp_m6
app.app-name=E-TravelGo

spring.datasource.url=jdbc:h2:mem:mvp_m6
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

